# Generated by Django 5.0.6 on 2025-05-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название динамической модели",
                        max_length=255,
                        verbose_name="Название модели",
                    ),
                ),
                (
                    "fields_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON конфигурация полей модели",
                        verbose_name="Конфигурация полей",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Уникальное название таблицы в БД",
                        max_length=255,
                        unique=True,
                        verbose_name="Название таблицы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Описание назначения модели",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, активна ли модель",
                        verbose_name="Активна",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Сайт, к которому принадлежит модель",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_models",
                        to="sites.site",
                        verbose_name="Сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Динамическая модель",
                "verbose_name_plural": "Динамические модели",
                "ordering": ["-created_at"],
                "unique_together": {("site", "name")},
            },
        ),
        migrations.CreateModel(
            name="DynamicModelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON данные записи",
                        verbose_name="Данные",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, опубликована ли запись",
                        verbose_name="Опубликовано",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dynamic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_entries",
                        to="dynamic_models.dynamicmodel",
                        verbose_name="Динамическая модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные динамической модели",
                "verbose_name_plural": "Данные динамических моделей",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dynamic_model", "is_published"],
                        name="dynamic_mod_dynamic_95e8b5_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="dynamic_mod_created_f9aa32_idx"
                    ),
                ],
            },
        ),
    ]
