# Generated by Django 5.0.6 on 2025-05-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Отображаемое название сайта",
                        max_length=255,
                        verbose_name="Название сайта",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Уникальный домен сайта (например: example.com)",
                        max_length=255,
                        unique=True,
                        verbose_name="Домен",
                    ),
                ),
                (
                    "header_scripts",
                    models.TextField(
                        blank=True,
                        help_text="HTML код скриптов для вставки в head секцию",
                        verbose_name="Скрипты в header",
                    ),
                ),
                (
                    "footer_scripts",
                    models.TextField(
                        blank=True,
                        help_text="HTML код скриптов для вставки в footer секцию",
                        verbose_name="Скрипты в footer",
                    ),
                ),
                (
                    "main_screen_settings",
                    models.JSONField(
                        default=dict,
                        help_text="JSON с настройками главной страницы",
                        verbose_name="Настройки главного экрана",
                    ),
                ),
                (
                    "seo_settings",
                    models.JSONField(
                        default=dict,
                        help_text="JSON с SEO настройками сайта",
                        verbose_name="SEO настройки",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon сайта",
                        null=True,
                        upload_to="sites/icons/",
                        verbose_name="Иконка сайта",
                    ),
                ),
                (
                    "default_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение, используемое по умолчанию",
                        null=True,
                        upload_to="sites/defaults/",
                        verbose_name="Изображение по умолчанию",
                    ),
                ),
                (
                    "main_screen_image",
                    models.ImageField(
                        blank=True,
                        help_text="Основное изображение для главной страницы",
                        null=True,
                        upload_to="sites/main/",
                        verbose_name="Изображение главного экрана",
                    ),
                ),
                (
                    "error_403_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для страницы ошибки 403",
                        null=True,
                        upload_to="sites/errors/",
                        verbose_name="Изображение ошибки 403",
                    ),
                ),
                (
                    "error_404_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для страницы ошибки 404",
                        null=True,
                        upload_to="sites/errors/",
                        verbose_name="Изображение ошибки 404",
                    ),
                ),
                (
                    "error_4xx_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для страниц ошибок 4xx",
                        null=True,
                        upload_to="sites/errors/",
                        verbose_name="Изображение ошибки 4xx",
                    ),
                ),
                (
                    "error_5xx_image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для страниц ошибок 5xx",
                        null=True,
                        upload_to="sites/errors/",
                        verbose_name="Изображение ошибки 5xx",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, активен ли сайт",
                        verbose_name="Активен",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Пользователь-владелец сайта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_sites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сайт",
                "verbose_name_plural": "Сайты",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["domain"], name="sites_site_domain_460169_idx"
                    ),
                    models.Index(
                        fields=["owner", "is_active"],
                        name="sites_site_owner_i_ea2db0_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="sites_site_created_8f889d_idx"
                    ),
                ],
            },
        ),
    ]
