# Generated by Django 5.0.6 on 2025-06-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('author', 'Автор'), ('editor', 'Редактор')], default='author', help_text='Роль, которую пользователь хочет получить', max_length=20, verbose_name='Запрашиваемая роль')),
                ('message', models.TextField(blank=True, help_text='Дополнительная информация о запросе', verbose_name='Сообщение от пользователя')),
                ('admin_response', models.TextField(blank=True, help_text='Комментарий администратора к решению', verbose_name='Ответ администратора')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='pending', help_text='Текущий статус запроса', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Администратор, рассмотревший запрос', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_site_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('site', models.ForeignKey(help_text='Сайт, к которому запрашивается доступ', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='sites.site', verbose_name='Сайт')),
                ('user', models.ForeignKey(help_text='Пользователь, запрашивающий доступ', on_delete=django.db.models.deletion.CASCADE, related_name='site_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на доступ к сайту',
                'verbose_name_plural': 'Запросы на доступ к сайтам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='sites_siter_user_id_9c148c_idx'), models.Index(fields=['site', 'status'], name='sites_siter_site_id_32b578_idx'), models.Index(fields=['-created_at'], name='sites_siter_created_d0fdb5_idx'), models.Index(fields=['status', '-created_at'], name='sites_siter_status_057376_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='siterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'site'), name='unique_pending_site_request'),
        ),
    ]
