# Generated by Django 5.0.6 on 2025-06-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_siterequest_siterequest_unique_pending_site_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=128, verbose_name='Access Key')),
                ('secret_key', models.CharField(max_length=128, verbose_name='Secret Key')),
                ('bucket_name', models.CharField(max_length=128, verbose_name='Bucket Name')),
                ('endpoint', models.CharField(default='https://storage.yandexcloud.net', max_length=256, verbose_name='Endpoint')),
                ('region', models.CharField(default='ru-central1', max_length=64, verbose_name='Регион')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to='sites.site')),
            ],
            options={
                'verbose_name': 'Настройки Object Storage',
                'verbose_name_plural': 'Object Storage для сайтов',
            },
        ),
    ]
