# Generated by Django 5.0.6 on 2025-05-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок страницы",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="HTML содержание страницы",
                        verbose_name="Содержание (HTML)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-дружественный идентификатор страницы",
                        max_length=255,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Основное изображение страницы",
                        null=True,
                        upload_to="pages/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет, опубликована ли страница",
                        verbose_name="Опубликована",
                    ),
                ),
                (
                    "page_components",
                    models.JSONField(
                        default=list,
                        help_text="JSON массив с компонентами страницы для визуального конструктора",
                        verbose_name="Компоненты страницы",
                    ),
                ),
                (
                    "compiled_css",
                    models.TextField(
                        blank=True,
                        help_text="CSS стили, сгенерированные из компонентов",
                        verbose_name="Скомпилированный CSS",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO заголовок страницы",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO описание страницы",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO ключевые слова",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "is_homepage",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли эта страница главной страницей сайта",
                        verbose_name="Главная страница",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Кастомный шаблон для рендеринга страницы",
                        max_length=100,
                        verbose_name="Название шаблона",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок отображения в меню",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время публикации страницы",
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор страницы",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Сайт, к которому принадлежит страница",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sites.site",
                        verbose_name="Сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "is_published"],
                        name="pages_page_site_id_1f8407_idx",
                    ),
                    models.Index(
                        fields=["site", "is_homepage"],
                        name="pages_page_site_id_21aae5_idx",
                    ),
                    models.Index(fields=["slug"], name="pages_page_slug_3e99a9_idx"),
                    models.Index(
                        fields=["sort_order"], name="pages_page_sort_or_59bd4d_idx"
                    ),
                ],
                "unique_together": {("site", "slug")},
            },
        ),
    ]
