# Generated by Django 5.0.6 on 2025-06-21 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0003_sitestoragesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название источника')),
                ('platform', models.CharField(choices=[('wordpress', 'WordPress'), ('drupal', 'Drupal'), ('joomla', 'Joomla'), ('csv', 'CSV файл'), ('json', 'JSON файл'), ('xml', 'XML файл')], max_length=50, verbose_name='Платформа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Источник импорта',
                'verbose_name_plural': 'Источники импорта',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('content_types', models.JSONField(default=list, verbose_name='Типы контента для импорта')),
                ('import_settings', models.JSONField(default=dict, verbose_name='Настройки импорта')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='imports/', verbose_name='Файл источника')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего элементов')),
                ('processed_items', models.PositiveIntegerField(default=0, verbose_name='Обработано элементов')),
                ('imported_items', models.PositiveIntegerField(default=0, verbose_name='Импортировано элементов')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Ошибок импорта')),
                ('results', models.JSONField(default=dict, verbose_name='Результаты импорта')),
                ('errors', models.JSONField(default=list, verbose_name='Ошибки импорта')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('target_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='sites.site', verbose_name='Целевой сайт')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='import_export.importsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех')], max_length=20, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('item_id', models.CharField(blank=True, max_length=255, verbose_name='ID элемента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='import_export.importjob', verbose_name='Задача импорта')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(max_length=255, verbose_name='Поле источника')),
                ('target_field', models.CharField(max_length=255, verbose_name='Целевое поле')),
                ('field_type', models.CharField(max_length=50, verbose_name='Тип поля')),
                ('transformation_rules', models.JSONField(default=dict, verbose_name='Правила трансформации')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('default_value', models.TextField(blank=True, verbose_name='Значение по умолчанию')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='import_export.importjob', verbose_name='Задача импорта')),
            ],
            options={
                'verbose_name': 'Маппинг полей',
                'verbose_name_plural': 'Маппинги полей',
                'unique_together': {('job', 'source_field')},
            },
        ),
    ]
