# Generated by Django 5.0.6 on 2025-05-29 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок поста",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Основное содержание поста", verbose_name="Содержание"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-дружественный идентификатор поста",
                        max_length=255,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Основное изображение поста",
                        null=True,
                        upload_to="posts/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Определяет, опубликован ли пост",
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO заголовок страницы",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO описание страницы",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO ключевые слова",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Счетчик просмотров поста",
                        verbose_name="Количество просмотров",
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Примерное время чтения в минутах",
                        verbose_name="Время чтения (мин)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время публикации поста",
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор поста",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Сайт, к которому принадлежит пост",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="sites.site",
                        verbose_name="Сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "is_published"],
                        name="posts_post_site_id_8c7498_idx",
                    ),
                    models.Index(
                        fields=["author", "is_published"],
                        name="posts_post_author__c82edc_idx",
                    ),
                    models.Index(fields=["slug"], name="posts_post_slug_59b922_idx"),
                    models.Index(
                        fields=["-published_at"], name="posts_post_publish_afa8cc_idx"
                    ),
                ],
                "unique_together": {("site", "slug")},
            },
        ),
    ]
