# Generated by Django 5.0.6 on 2025-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('password', 'Защищенный паролем')], default='public', max_length=20, verbose_name='Видимость'),
        ),
    ]
