# Generated by Django 5.0.6 on 2025-06-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет'),
        ),
    ]
