# Generated by Django 5.0.6 on 2025-06-07 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter (X)'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'ВКонтакте'), ('odnoklassniki', 'Одноклассники'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('discord', 'Discord')], max_length=20, verbose_name='Социальная сеть')),
                ('url', models.URLField(help_text='Полная ссылка на профиль', verbose_name='Ссылка')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='setting',
            name='settings_se_site_id_505c40_idx',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='site',
        ),
        migrations.AddField(
            model_name='socialnetworksetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddConstraint(
            model_name='socialnetworksetting',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_social_network'),
        ),
    ]
